---
# Copyright (C) 2025 Robert Wimmer
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (Rocky Linux) Install wireguard-tools package
  ansible.builtin.dnf:
    name: wireguard-tools
    state: present
    update_cache: "{{ wireguard_update_cache }}"
